services:
  frontend:
    depends_on: !reset []

  reverse-proxy:
    depends_on: !reset
      - frontend

  backend:
    restart: no
    profiles:
      - do_not_start

  database:
    restart: no
    profiles:
      - do_not_start
