/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 *  The OpenAPI 3.0 specification for the REST API of the Software Templates Hub: Create your project from cookiecutter templates via web interface: [https://templates.services.fedcloud.eu](https://templates.services.fedcloud.eu)  - [Templates Hub](https://templates.services.fedcloud.eu) - [How to add your template to the Hub](https://github.com/m-team-kit/templates-hub/blob/main/README.md) 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CutterOption } from './cutter-option.js';
// May contain unused imports in some cases
// @ts-ignore
import { Default } from './default.js';
// May contain unused imports in some cases
// @ts-ignore
import { FieldType } from './field-type.js';

/**
 * 
 * @export
 * @interface CutterField
 */
export interface CutterField {
    /**
     * 
     * @type {Default}
     * @memberof CutterField
     */
    'default': Default;
    /**
     * 
     * @type {string}
     * @memberof CutterField
     */
    'name': string;
    /**
     * 
     * @type {Array<CutterOption>}
     * @memberof CutterField
     */
    'options'?: Array<CutterOption> | null;
    /**
     * 
     * @type {string}
     * @memberof CutterField
     */
    'prompt'?: string | null;
    /**
     * 
     * @type {FieldType}
     * @memberof CutterField
     */
    'type': FieldType;
}



