/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 *  The OpenAPI 3.0 specification for the REST API of the Software Templates Hub: Create your project from cookiecutter templates via web interface: [https://templates.services.fedcloud.eu](https://templates.services.fedcloud.eu)  - [Templates Hub](https://templates.services.fedcloud.eu) - [How to add your template to the Hub](https://github.com/m-team-kit/templates-hub/blob/main/README.md) 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Template
 */
export interface Template {
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    'gitCheckout': string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    'gitLink': string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    'language': string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    'picture': string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    'repoFile': string;
    /**
     * 
     * @type {number}
     * @memberof Template
     */
    'score': number | null;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    'summary': string;
    /**
     * 
     * @type {Set<string>}
     * @memberof Template
     */
    'tags': Set<string>;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    'title': string;
}

