import { NextPage } from 'next';
import { useQuery } from 'react-query';
import {
    BACKEND_ROUTE,
    COOKIECUTTER_TEMPLATE_URL,
    GIT_BRANCH_NAME,
    GIT_REPO_URL,
} from 'lib/configuration';
import { LegalField } from 'lib/template';
import Form from '../components/Form';
import { useState } from 'react';
import Navbar from '../components/Navbar';
import { useAuth } from 'react-oidc-context';

type Template = {
    templateUrl: string;
    helpUrl?: string;
    gitRepo: string;
    gitBranch: string;
    name: string;
};

const deepHdcMaster: Template = {
    templateUrl:
        'https://raw.githubusercontent.com/deephdc/cookiecutter-deep/master/cookiecutter.json',
    gitRepo: GIT_REPO_URL,
    gitBranch: 'master',
    name: 'deephdc/cookiecutter-deep:master',
};
const deepHdcAdvanced: Template = {
    templateUrl: COOKIECUTTER_TEMPLATE_URL,
    helpUrl:
        COOKIECUTTER_TEMPLATE_URL.substring(0, COOKIECUTTER_TEMPLATE_URL.lastIndexOf('.')) +
        '-help.json',
    gitRepo: GIT_REPO_URL,
    gitBranch: GIT_BRANCH_NAME,
    name: 'deephdc/cookiecutter-deep:advanced',
};

const TemplateForm = () => {
    const [templateUrl, setTemplateUrl] = useState(deepHdcMaster.templateUrl);
    const [helpUrl, setHelpUrl] = useState<string | undefined>(undefined);
    const [gitRepo, setGitRepo] = useState(deepHdcMaster.gitRepo);
    const [gitBranch, setGitBranch] = useState(deepHdcMaster.gitBranch);

    const templates: Template[] = [deepHdcMaster, deepHdcAdvanced];

    const fields = useQuery(
        [templateUrl, gitRepo, gitBranch],
        async () => {
            const response = await fetch(
                '/api/template?' +
                    new URLSearchParams(
                        helpUrl
                            ? {
                                  url: templateUrl,
                                  helpUrl: helpUrl,
                              }
                            : { url: templateUrl }
                    )
            );
            // TODO: less dirty approach?
            return (response.json as () => Promise<LegalField[]>)();
        },
        { refetchOnWindowFocus: false }
    );

    return (
        <>
            <select
                onChange={(e) => {
                    const template = templates[parseInt(e.target.value)];
                    setTemplateUrl(template.templateUrl);
                    setGitRepo(template.gitRepo);
                    setGitBranch(template.gitBranch);
                    setHelpUrl(template.helpUrl);
                }}
            >
                {templates.map((t, i) => {
                    return (
                        <option key={t.gitRepo + t.gitBranch} value={i}>
                            {t.name}
                        </option>
                    );
                })}
            </select>
            <form
                action={
                    BACKEND_ROUTE +
                    '?' +
                    new URLSearchParams({
                        url: templateUrl,
                        git_repo: gitRepo,
                        git_branch: gitBranch,
                    })
                }
                method="post"
            >
                <p>
                    Filling this web-form will generate a .zip file with the folders generated by
                    the cookiecutter. It will contain everything necessary to start your
                    DEEP-Project.
                </p>
                <div>{fields.isSuccess && <Form fields={fields.data} />}</div>
                <input className="button" type="submit" value="Generate" />
            </form>
        </>
    );
};

const Home: NextPage = () => {
    const auth = useAuth();

    return (
        <>
            <Navbar />
            <section className="header" style={{ paddingTop: '7em' }}></section>
            <div className="container">
                <main>
                    {auth.isAuthenticated ? (
                        <TemplateForm />
                    ) : (
                        <>
                            <p>Please log in!</p>
                            <button onClick={() => auth.signinRedirect()}>Login</button>
                        </>
                    )}
                </main>
            </div>
            <footer id="contentinfo" className="body">
                <div className="footer">
                    <div className="container" style={{ maxWidth: '1600px' }}>
                        <div className="row">
                            <div className="one column">
                                <img src="images/ec-logo.png" />
                            </div>
                            <div className="four columns">
                                This project has received funding from the European Union’s Horizon
                                2020 research and innovation programme under grant agreement No
                                777435.
                            </div>
                            <div className="four columns">
                                <ul className="">
                                    <li>
                                        <a
                                            href="https://docs.deep-hybrid-datacloud.eu"
                                            title="Documentation"
                                        >
                                            <span className="fas fa-book"></span>
                                            Documentation
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="https://github.com/deephdc/"
                                            title="Github Profile"
                                        >
                                            <span className="fab fa-github"></span>
                                            GitHub
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="https://hub.docker.com/u/deephdc/"
                                            title="DockerHub organization"
                                        >
                                            <span className="fab fa-docker"></span>
                                            DockerHub
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="https://twitter.com/DEEP_eu"
                                            title="Twitter Profile"
                                        >
                                            <span className="fab fa-twitter"></span>
                                            Twitter
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="https://www.researchgate.net/project/DEEP-Hybrid-DataCloud"
                                            title="ResearchGate Project page"
                                        >
                                            <span className="fab fa-researchgate"></span>
                                            ResearchGate
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div className="one column">
                                <img className="logo" src="/images/logo-deep-solid-white.png" />
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </>
    );
};

export default Home;
