import { NextPage } from 'next';
import { useQuery } from 'react-query';
import {
    BACKEND_ROUTE,
    COOKIECUTTER_HELP_URL,
    COOKIECUTTER_TEMPLATE_URL,
} from '../lib/configuration';
import { LegalField } from '../lib/template';
import Form from '../components/Form';

const Home: NextPage = () => {
    const fields = useQuery(
        COOKIECUTTER_TEMPLATE_URL,
        async () => {
            const response = await fetch(
                '/api/template?' +
                    new URLSearchParams({
                        url: COOKIECUTTER_TEMPLATE_URL,
                        helpUrl: COOKIECUTTER_HELP_URL,
                    })
            );
            // TODO: less dirty approach?
            return (response.json as () => Promise<LegalField[]>)();
        },
        { refetchOnWindowFocus: false }
    );

    return (
        <div>
            <main>
                <div className="testbox">
                    <form action={BACKEND_ROUTE} method="post">
                        <h1>Cookiecutter Webform</h1>
                        <p>
                            Filling this web-form will generate a .zip file with the folders
                            generated by the cookiecutter. It will contain everything necessary to
                            start your DEEP-Project.
                        </p>
                        <div style={{ padding: '0.25em' }}>
                            {fields.isSuccess && <Form fields={fields.data} />}
                        </div>
                        {/*
        {% if data[0]|length == 3 %}
        {% for key, dsc, place in data %}
          {{ dsc }}
          {% if key != "Press Enter and configure" %}
            {% if place is not string %}
              <select name="{{ key }}" class="selectpicker form-control">
                {% for o in place %}
                <option value="{{ o }}">{{ o }}</option>
                {% endfor %}
              </select><br>
            {% else %}
               <br><input class="input" type="text" name = "{{ key }}" placeholder = "{{ place }}"><br>
            {% endif %}
          {% endif %}
        <br>
        {% endfor %}
        {% else %}
        {% for input,key in data %}
          {{ input }}
          {% if key != "Press Enter and configure" %}
            {% if key is not string %}
              <select name="{{ input }}" class="selectpicker form-control">
                {% for o in key %}
                <option value="{{ o }}">{{ o }}</option>
                {% endfor %}
              </select><br>
            {% else %}
               <br><input class="input" type="text" name = "{{ input }}" placeholder = "{{ key }}"><br>
            {% endif %}
          {% endif %}
        <br>
        {% endfor %}
        {% endif %}
        */}
                        <input className="button" type="submit" />
                    </form>
                </div>
            </main>
        </div>
    );
};

export default Home;
