/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 *  The OpenAPI 3.0 specification for the REST API of the Software Templates Hub: Create your project from cookiecutter templates via web interface: [https://templates.services.fedcloud.eu](https://templates.services.fedcloud.eu)  - [Templates Hub](https://templates.services.fedcloud.eu) - [How to add your template to the Hub](https://github.com/m-team-kit/templates-hub/blob/main/README.md) 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration.js';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common.js';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base.js';
// @ts-ignore
import { CutterField } from '../models/index.js';
// @ts-ignore
import { NotFound } from '../models/index.js';
// @ts-ignore
import { NotImplemented } from '../models/index.js';
// @ts-ignore
import { ServerError } from '../models/index.js';
// @ts-ignore
import { Unauthorized } from '../models/index.js';
// @ts-ignore
import { Unprocessable } from '../models/index.js';
/**
 * ProjectApi - axios parameter creator
 * @export
 */
export const ProjectApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Use this method to fetch fields of the cookiecutter template to build the web form.
         * @summary (Public) Fetches fields of the cookiecutter template.
         * @param {string} uuid UUID of the template to be used for generating a new software project.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchFields: async (uuid: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            assertParamExists('fetchFields', 'uuid', uuid)
            const localVarPath = `/project/{uuid}`
                .replace(`{${"uuid"}}`, encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this method to generate software project using the specific template. Generated project is returned as `.zip` file.
         * @summary (User) Generate software project from the template.
         * @param {string} uuid UUID of the template to be used for generating a new software project.
         * @param {{ [key: string]: string; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateProject: async (uuid: string, requestBody: { [key: string]: string; }, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            assertParamExists('generateProject', 'uuid', uuid)
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('generateProject', 'requestBody', requestBody)
            const localVarPath = `/project/{uuid}:generate`
                .replace(`{${"uuid"}}`, encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectApi - functional programming interface
 * @export
 */
export const ProjectApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProjectApiAxiosParamCreator(configuration)
    return {
        /**
         * Use this method to fetch fields of the cookiecutter template to build the web form.
         * @summary (Public) Fetches fields of the cookiecutter template.
         * @param {string} uuid UUID of the template to be used for generating a new software project.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchFields(uuid: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CutterField>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchFields(uuid, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Use this method to generate software project using the specific template. Generated project is returned as `.zip` file.
         * @summary (User) Generate software project from the template.
         * @param {string} uuid UUID of the template to be used for generating a new software project.
         * @param {{ [key: string]: string; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateProject(uuid: string, requestBody: { [key: string]: string; }, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateProject(uuid, requestBody, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ProjectApi - factory interface
 * @export
 */
export const ProjectApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProjectApiFp(configuration)
    return {
        /**
         * Use this method to fetch fields of the cookiecutter template to build the web form.
         * @summary (Public) Fetches fields of the cookiecutter template.
         * @param {string} uuid UUID of the template to be used for generating a new software project.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchFields(uuid: string, options?: any): AxiosPromise<Array<CutterField>> {
            return localVarFp.fetchFields(uuid, options).then((request) => request(axios, basePath));
        },
        /**
         * Use this method to generate software project using the specific template. Generated project is returned as `.zip` file.
         * @summary (User) Generate software project from the template.
         * @param {string} uuid UUID of the template to be used for generating a new software project.
         * @param {{ [key: string]: string; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateProject(uuid: string, requestBody: { [key: string]: string; }, options?: any): AxiosPromise<File> {
            return localVarFp.generateProject(uuid, requestBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProjectApi - object-oriented interface
 * @export
 * @class ProjectApi
 * @extends {BaseAPI}
 */
export class ProjectApi extends BaseAPI {
    /**
     * Use this method to fetch fields of the cookiecutter template to build the web form.
     * @summary (Public) Fetches fields of the cookiecutter template.
     * @param {string} uuid UUID of the template to be used for generating a new software project.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApi
     */
    public fetchFields(uuid: string, options?: AxiosRequestConfig) {
        return ProjectApiFp(this.configuration).fetchFields(uuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this method to generate software project using the specific template. Generated project is returned as `.zip` file.
     * @summary (User) Generate software project from the template.
     * @param {string} uuid UUID of the template to be used for generating a new software project.
     * @param {{ [key: string]: string; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApi
     */
    public generateProject(uuid: string, requestBody: { [key: string]: string; }, options?: AxiosRequestConfig) {
        return ProjectApiFp(this.configuration).generateProject(uuid, requestBody, options).then((request) => request(this.axios, this.basePath));
    }
}

